development:
  host: <%= ENV["AD_HOST"] %>
  port: <%= ENV["AD_PORT"] %>
  base: <%= ENV["AD_BASE"] %>

test:
  host: <%= ENV["AD_HOST"] %>
  port: <%= ENV["AD_PORT"] %>
  # default_domain: EXAMPLEDOMAIN
  base: <%= ENV["AD_BASE"] %>

production:
  host: <%= ENV["AD_HOST"] %>
  port: <%= ENV["AD_PORT"] %>
  # default_domain: EXAMPLEDOMAIN
  base: <%= ENV["AD_BASE"] %>
