development:
  host: <%= ENV["LDAP_HOST"] %>
  port: <%= ENV["LDAP_PORT"] %>
  base: <%= ENV["LDAP_BASE"] %>

test:
  host: examplehost
  port: 389
  default_domain: EXAMPLEDOMAIN
  base: examplebase # OU=US-Tampa Bay,OU=North America,OU=Accounts,DC=ourdomain,DC=org

production:
  host: examplehost
  port: 389
  default_domain: EXAMPLEDOMAIN
  base: examplebase # OU=US-Tampa Bay,OU=North America,OU=Accounts,DC=ourdomain,DC=org
